<?php if (! empty($this->display_exceptions)): ?>

    <?php if (isset($this->exception['options']['assets']['js'])): ?>
        <?php foreach ($this->exception['options']['assets']['js'] as $js): ?>
            <?= $this->headScript()->appendFile($js) ?>
        <?php endforeach ?>
    <?php endif ?>

    <?php if (isset($this->exception['options']['assets']['css'])): ?>
        <?php foreach ($this->exception['options']['assets']['css'] as $css): ?>
            <?= $this->headLink()->appendStylesheet($css) ?>
        <?php endforeach ?>
    <?php endif ?>


    <style>
        #error-manager pre {
            font-size: 12px;
            margin-bottom: 0;
        }
        #error-manager pre .active {
            background-color: #fcf8e3;
        }
        #error-manager li {
            line-height: 17px;
        }
        #error-manager .accordion a {
            text-decoration: none;
        }
        #error-manager .well,
        #error-manager .alert {
            margin-bottom: 10px;
            padding: 10px;
        }
        #error-manager .accordion-inner .alert {
            font-size: 12px;
            line-height: 15px;
        }
        #error-manager .title {
            padding: 10px;
        }
        #error-manager .title .lead {
            margin-bottom: 0;
        }
        #error-manager .title h3 {
            line-height: 30px;
        }
    </style>

    <div id="error-manager">
        <?php foreach ($this->exception['exceptions'] as $eKey => $exception): ?>
            <section>
                <header>
                    <div class="well title">
                        <h3 class="text-error"><?= $exception['name'] ?></h3>
                        <div class="lead muted"><?= $exception['message'] ?></div>
                    </div>
                </header>

                <?php if ($exception['documentation']): ?>
                    <div class="alert alert-success">
                        <?= nl2br($exception['documentation']) ?>
                    </div>
                <?php endif ?>

                <?php if ($exception['trace']): ?>
                    <div class="accordion" id="acc<?= $eKey ?>">
                        <?php foreach($exception['trace'] as $key => $trace): ?>
                            <div class="accordion-group">

                                <div class="accordion-heading clearfix">
                                    <span class="accordion-toggle" data-toggle="collapse" data-parent="#acc<?= $eKey ?>" href="#trace<?= $eKey.$key?>-content">
                                        <small class="linenum label label-info">@<?= $trace['line'] ?></small>
                                        <a href="">
                                            <?= $this->errFileName($trace['file']) ?>
                                        </a>
                                    </span>
                                </div>

                                <div id="trace<?= $eKey.$key?>-content" class="accordion-body collapse">
                                    <div class="accordion-inner">
                                        <?php if ($trace['documentation']): ?>
                                            <header class="alert alert-info">
                                                <?= nl2br($trace['documentation']) ?>
                                            </header>
                                        <?php endif ?>
                                        <p class="well"><?= $this->errTraceMethod($trace) ?></p>
                                        <?php if (isset($trace['line'])): ?>
                                            <pre class="prettyprint linenums:<?= (key($trace['context']) + 1) ?> linenums lang-php" data-active-line="<?= $trace['line'] ?>">
<?= implode($trace['context']) ?>
</pre>
                                        <?php endif ?>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach ?>
                    </div>
                <?php endif ?>

            </section>
        <?php endforeach ?>
    </div>
    <script type="text/javascript">
        !function ($) {
            $(function(){
                if (window.prettyPrint) {
                    prettyPrint();
                    $('pre').each(function(){ // highlight the active line
                        var lines      = $(this).find('li'),
                            activeLine = parseInt($(this).attr('data-active-line')),
                            firstLine  = parseInt(lines.first().attr('value'));

                        lines.eq(activeLine - firstLine).addClass('active');
                    });
                }
            });
        }(window.jQuery);
    </script>
<?php endif ?>