<?php if (! empty($this->display_exceptions)): ?>

    <?php require __DIR__ . '/_assets.phtml' ?>

    <style>
        #error-manager li {
            line-height: 17px;
        }
        #error-manager .panel a {
            text-decoration: none;
        }
        #error-manager .alert {
            margin-bottom: 10px;
            padding: 10px;
        }
        #error-manager .panel-heading {
            padding: 5px;
        }
        #error-manager .panel .alert {
            font-size: 12px;
            line-height: 15px;
        }
        #error-manager h3 {
            margin-top: 10px;
        }
    </style>

    <div id="error-manager">
        <?php foreach ($this->data['exceptions'] as $eKey => $exception): ?>
            <section class="panel panel-danger">
                <header class="panel-heading clearfix">
                    <div class="pull-left">
                        <h3><?= $eKey+1 ?>. <?= $exception['name'] ?></h3>
                        <?= $exception['message'] ?>
                    </div>
                    <div class="pull-right">
                        <h3>
                            <a class="btn btn-sm btn-primary"
                               href="<?= sprintf('https://github.com/%s/issues/new?title=%s&body=%s', $options['repository'], $exception['name'], $exception['message'])?>"
                               target="_blank"
                               >
                                <i class="glyphicon glyphicon-export"></i>
                                <?= $this->translate('Report on Github') ?>
                            </a>
                        </h3>
                    </div>
                </header>

                <article class="panel-body">
                    <?php if ($exception['documentation']): ?>
                        <div class="alert alert-success">
                            <?= nl2br($exception['documentation']) ?>
                        </div>
                    <?php endif ?>

                    <?php if ($exception['trace']): ?>
                        <div class="panel-group" id="acc<?= $eKey ?>">
                            <?php foreach($exception['trace'] as $key => $trace): ?>
                                <div class="panel panel-default">

                                    <div class="panel-heading">
                                        <div class=" accordion-toggle" data-toggle="collapse" data-parent="#acc<?= $eKey ?>" href="#trace<?= $eKey.$key?>-content">
                                            <?= $this->errContextLineColor($trace) ?>
                                            <a><?= $this->errFileName($trace['file']) ?></a>
                                        </div>
                                    </div>

                                    <div id="trace<?= $eKey.$key ?>-content" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <?php if ($trace['documentation']): ?>
                                                <header class="alert alert-info">
                                                    <?= nl2br($trace['documentation']) ?>
                                                </header>
                                            <?php endif ?>
                                            <blockquote>
                                                <?= $this->errTraceMethod($trace) ?>
                                            </blockquote>
                                            <?php if (isset($trace['line'])): ?>
<pre class="prettyprint linenums:<?= (key($trace['context']) + 1) ?> linenums lang-php" data-active-line="<?= $trace['line'] ?>">
<?= implode($trace['context']) ?>
</pre>
                                            <?php endif ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach ?>
                        </div>
                    <?php endif ?>
                </article>
            </section>
        <?php endforeach ?>
    </div>
    <?php require __DIR__ . '/_footer.phtml' ?>
<?php endif ?>